### ISSUE TITLE
Add support for older shading devices

### ISSUE THREAD

**Issue by hans99** [jankrib/ha-xcomfort-bridge#24]
For the older CJAU-01/03 shading device position is not supported and I think that is why I get this error in home assistant:

```
2023-08-11 11:00:06.719 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback Entity.async_write_ha_state()
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 746, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 810, in _async_write_ha_state
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/cover/__init__.py", line 284, in state_attributes
    if (current := self.current_cover_position) is not None:
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xcomfort_bridge/cover.py", line 149, in current_cover_position
    return 100 - self._state.position
           ~~~~^~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'

```

Would be good if this device is reported differently.
Let me know if this is difficult without the actual device and I will have a look at it when time permits...

**Comment by hans99** [comment]
No more errors now, thanks!!
