### ISSUE TITLE
Error adding cover / shutters

### ISSUE THREAD

**Issue by Makestudio20** [jankrib/ha-xcomfort-bridge#26]
First of all, great work on putting this to work. Works brilliant for my light that are connected with the X Comfort Bridge.

I do get an error with my sunshades though when Home Assistant is loading this platform "Error adding entities for domain cover with platform xcomfort_bridge". This is what I find in the log. Any idea on how I can fix this?

Logger: homeassistant.components.cover
Source: helpers/entity_platform.py:507
Integration: Cover ([documentation](https://www.home-assistant.io/integrations/cover), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+cover%22))

Error adding entities for domain cover with platform xcomfort_bridge
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1057, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 822, in _async_generate_attributes
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/cover/__init__.py", line 284, in state_attributes
    if (current := self.current_cover_position) is not None:
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xcomfort_bridge/cover.py", line 149, in current_cover_position
    return 100 - self._state.position
           ~~~~^~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'

**Comment by Makestudio20** [comment]
![Screenshot 2024-02-19 at 10 51 52](https://github.com/jankrib/ha-xcomfort-bridge/assets/77848160/d67a660c-a71b-4998-837a-0c8cfceed56a)

Just bumping this because I'm curious if anyone else is having this issue? Home Assistant does recognise the shades in the integration, but when clicking the device it shows: "this entity is no longer provided by the comfort_bridge integration with the above log details... Would be great if we could get this working. I don't have enough experience with programming myself unfortunately.

**Comment by jankrib** [comment]
@Makestudio20 Can you verify that it works after https://github.com/jankrib/ha-xcomfort-bridge/pull/28

**Comment by Makestudio20** [comment]
Thanks very much for the fix! Actually the XComfort Bridge itself annoyed me so much that I have decided to swap the devices I used for Shelly's. So I can't check if it works anymore. Sorry that this caused you extra work, hopefully someone else might still think this is a useful update.
